### ISSUE TITLE
Add new affirmation check for variables that end in .x or .y indicating--a likely merge error

### ISSUE THREAD

**Issue by ddsjoberg** [pcctc/affirm#15]
@tgerke @shannonpileggi I am happy to add this function, but can you chime in with potential names? `affirm_no_bad_join_colnames()` just doesn't flow like I thought it would 😆

**Comment by shannonpileggi** [comment]
how about `affirm_clean_join()` or `affirm_clean_join_colnames()`

**Comment by ddsjoberg** [comment]
I love both! Let's go with `affirm_clean_join()` 🎆
