### ISSUE TITLE
Added excel formatting capability for `affirm_report_gt()`?

### ISSUE THREAD

**Issue by Meghansaha** [pcctc/affirm#23]
Maybe this isn't needed because it's for manual reviews right now...but do we want to explore hardcoding in excel formatting like filtering and basic style formatting like we do with croquet's [labelled_sheet](https://github.com/pcctc/croquet/blob/main/R/labelled_sheet.R) fxs? 

Currently, we have to ability to add variable labels... But I have not tried to see if I could add on/pipe in functions from `openxslx` to do this. Creating the issue here so I don't forget.

**Comment by shannonpileggi** [comment]
This would fit better in `affirm_report_excel` and is related to issue #26
