### ISSUE TITLE
Proposed `keep_all` or `keep` Arguments for Excel Report Summary Output

### ISSUE THREAD

**Issue by Meghansaha** [pcctc/affirm#38]
When using `affirm_report_excel()` for reporting, affirmations with an error percent of 0% do not print in the created summary table in the output.

This is most likely due to [line 63](https://github.com/pcctc/affirm/blob/main/R/affirm_report.R#L63) in `affirm_report.R` here:
https://github.com/pcctc/affirm/blob/fd07e24f9218a07f4caeba0ee9bf463e7c05f24c/R/affirm_report.R#L61-L67

I think we could either add an additional argument like `keep_all =` that would toggle between filtering out 0% affirmations or not.
<br>
-OR-
<br> 
We could get super fancy and have an argument like `keep =` where a list of affirmations that have to be "kept", no matter the error rate, are carried through to the final summary table. This would be helpful if there's only one or a few 0% affirmations that the user wants to keep.

**Comment by shannonpileggi** [comment]
I am ok with not introducing an argument and just having the default behavior be to export affirmations with an error percent of 0%.
